name: mlemix
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - dask=2023.10.1
  - dask-ml=2023.3.24
  - networkx=3.2.1
  - scikit-learn=1.3.2
  - pip
  - pip:
    - --editable ./
